apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podghosts.multicluster.admiralty.io
spec:
  group: multicluster.admiralty.io
  names:
    kind: PodGhost
    plural: podghosts
  scope: Namespaced
  version: v1alpha1
