apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: quay.io/admiralty/multicluster-controller-example-podghost
    workspace: ../../
    docker:
      dockerfilePath: examples/Dockerfile
      buildArgs:
        target: admiralty.io/multicluster-controller/examples/podghost/cmd/manager
deploy:
  kustomize:
    kustomizePath: kustomize/
