apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: manager
spec:
  template:
    spec:
      containers:
      - name: manager
        args: ["--contexts", "cluster1,cluster2"]
        image: quay.io/admiralty/multicluster-controller-example-helloworld
